name: dump

on:
  push:
    branches:
      - master
  schedule:
    - cron: "00 0 * * 0-7"

jobs:
  dump:
    runs-on: ubuntu-latest
    steps:
    - name: Dump github context
      run: echo "$GITHUB_CONTEXT"
      shell: bash
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}